SELECT USER
FROM DUAL;
---==>> SCOTT
SELECT *
FROM TBL_MEMBER
ORDER BY SID;

DESC TBL_MEMBER;
--==>>
/*
이름   널?       유형           
---- -------- ------------ 
SID  NOT NULL NUMBER       
NAME          VARCHAR2(30) 
TEL           VARCHAR2(40) 

*/

TRUNCATE TABLE TBL_MEMBER;
--==>> Table TBL_MEMBER이(가) 잘렸습니다.


DROP SEQUENCE MEMBERSEQ;
--==>> Sequence MEMBERSEQ이(가) 삭제되었습니다.

CREATE SEQUENCE MEMBERSEQ
NOCACHE;
--==>> Sequence MEMBERSEQ이(가) 생성되었습니다.

--> 한줄 구성
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '임유훤', '010-1111-1111')
;
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '정세찬', '010-2222-2222')
;
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '조세빈', '010-3333-3333')
;
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '강명철', '010-4444-4444')
;
--==>> 1 행 이(가) 삽입되었습니다. * 4

--> 한줄 구성
SELECT SID, NAME, TEL FROM TBL_MEMBER ORDER BY SID
;
--==>>
/*
1	임유훤	010-1111-1111
2	정세찬	010-2222-2222
3	조세빈	010-3333-3333
4	강명철	010-4444-4444
*/


SELECT COUNT(*) AS COUNT
FROM TBL_MEMBER;


--> 한줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBER
;

COMMIT;
--==>> 커밋 완료.







