SELECT USER
FROM DUAL;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, ROUND((KOR+ENG+MAT)/3,1) AS AVG FROM TBL_SCORE ORDER BY SID
;

INSERT INTO TBL_SCORE(SID,NAME,KOR,ENG,MAT) VALUES(SCORESEQ.NEXTVAL, '¿”¿Ø»Õ', 90, 80, 80)
;

SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;