/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-03 08:15:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Send09_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Send09.jspe</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function formChange(obj)\r\n");
      out.write("	{\r\n");
      out.write("		// 확인\r\n");
      out.write("		//alert(\"확인\");\r\n");
      out.write("		//alert(obj);\r\n");
      out.write("		//---==>> [object HTMLSelectElement]\r\n");
      out.write("		// alert(obj.form);\r\n");
      out.write("		//--==>> [object HTMLFormElement]\r\n");
      out.write("		\r\n");
      out.write("		// this.form(매개변수)\r\n");
      out.write("		// alert(obj);\r\n");
      out.write("		//--==>> [object HTMLFormElement]\r\n");
      out.write("		\r\n");
      out.write("		// ※ obj 변수(이 함수의 매개변수)에는 최종적으로 form 객체가 저장되어 있다.\r\n");
      out.write("		//	  → form에 대한 액션 처리 가능\r\n");
      out.write("		\r\n");
      out.write("		// document.forms[0];\r\n");
      out.write("		\r\n");
      out.write("		obj.submit();\r\n");
      out.write("		//-- 폼객체.submit()\r\n");
      out.write("		//   함수 호출을 통해 form객체의 데이터를\r\n");
      out.write("		//	 서버로 전송하는 것이 가능하다.\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>JSP를 이용한 데이터 송수신 실습 09</h1>\r\n");
      out.write("	<p>Send09.jsp● → Receive09.jsp○</p>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	○ 데이터 송수신 실습 09\r\n");
      out.write("	\r\n");
      out.write("		- 구구단 단수를 입력받아 서버로 전송해주는 형태의 페이지를 구현한다.\r\n");
      out.write("		\r\n");
      out.write("		- 단, submit 버튼 없이 이벤트 처리를 할 수 있도록 한다.\r\n");
      out.write("		\r\n");
      out.write("		  단 수 선택[--선택하세요-- ▼] → select \r\n");
      out.write("		  					2단\r\n");
      out.write("		  					3단\r\n");
      out.write("		  					4단\r\n");
      out.write("		  					5단\r\n");
      out.write("		  					6단\r\n");
      out.write("		  					7단\r\n");
      out.write("		  					8단\r\n");
      out.write("		  					9단\r\n");
      out.write("		 - select 선택 시\r\n");
      out.write("		   해당 단의 구구단 내용을 출력하는 JSP 페이지(Receive09.jsp)로\r\n");
      out.write("		   데이터를 전당하여 내용을 구성할 수 있도록 한다.\r\n");
      out.write("		   \r\n");
      out.write("		 - 사용자 최초 요청 페이지\r\n");
      out.write("		 	http://localhost:3306/WebApp06/Send09.jsp\r\n");
      out.write("		 	\r\n");
      out.write("		 - 물리적인 파일 구성\r\n");
      out.write("		 	·Send09.jsp\r\n");
      out.write("		 	·Recieve09.jsp\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write(" <div>\r\n");
      out.write(" 	<form action=\"Receive09.jsp\" method=\"get\" id=\"form01\">\r\n");
      out.write(" 		단 수 선택\r\n");
      out.write(" 		<!-- <select name=\"dan\" id=\"dan\" onchange=\"document.getElementById('form01').submit()\"> -->\r\n");
      out.write(" 		<select name=\"dan\" id=\"dan\" onchange=\"formChange(this.form)\">\r\n");
      out.write(" 			<option selected disabled >-- 선택하세요 --</option>\r\n");
      out.write(" 			<option value=\"1\" >1단</option>\r\n");
      out.write(" 			<option value=\"2\" >2단</option>\r\n");
      out.write(" 			<option value=\"3\">3단</option>\r\n");
      out.write(" 			<option value=\"4\">4단</option>\r\n");
      out.write(" 			<option value=\"5\">5단</option>\r\n");
      out.write(" 			<option value=\"6\">6단</option>\r\n");
      out.write(" 			<option value=\"7\">7단</option>\r\n");
      out.write(" 			<option value=\"8\">8단</option>\r\n");
      out.write(" 			<option value=\"9\">9단</option>\r\n");
      out.write(" 		</select>\r\n");
      out.write(" 	</form>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
