/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-04 06:03:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class SendAndReceive11_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	// 이전 페이지(SendAndReceive11_1.jsp)로부터 넘어온 데이터 수신
	//-- year, month
	
	String sYear = request.getParameter("year");
	String sMonth = request.getParameter("month");
	
	// Calendar 객체 생성
	//java.util.Calendar cal = java.util.Calendar.getInstance();
	Calendar cal = Calendar.getInstance();
	
	// 현재의 연, 월. 일 확인
	int nowYear = cal.get(Calendar.YEAR);			//-- 2026
	int nowMonth = cal.get(Calendar.MONTH) + 1 ; 	//-- 3
	int nowDay = cal.get(Calendar.DAY_OF_MONTH);	//-- 4
	
	// 표시할 달력의 연, 월 구성
	// → 페이지 최초 요청을 감안한 코드 처리
	int selectYear = nowYear;
	int selectMonth = nowMonth;
	
	// 페이지에 대한 요청이 최초 요청이 아닐 경우
	// → 선택한 값(이전 페이지로부터 수신한 값)을 활용한 달력의 연, 월 구성
	if(sYear != null || sMonth !=  null)
	{
		selectYear = Integer.parseInt(sYear);
		selectMonth = Integer.parseInt(sMonth);
	}
	
	// 테스트
	// out.print("<h1>selectYear: "+ selectYear + "</h1>");
	// out.print("<h1>selectMonth: "+ selectMonth + "</h1>");
	
	// 확인한 날짜로 연도 select option 구성
	//------------------------------------------------
 	// <option value="2016">2016</option>
	// <option value="2017">2017</option>
	// <option value="2018">2018</option>
	// 
	// <option value="2026" selected="selected">2026</option>
	// 				:
	// <option value="2034">2034</option>
	// <option value="2035">2035</option>
	// <option value="2036">2036</option> 
	//------------------------------------------------
	
	String yOption = "";
	for (int year=(selectYear-10); year<=(selectYear+10); year++)	// 2016 ~ 2036
	{
		// 관찰 ⓐ
		// yOption += "<option value='" +year +"'>"+year+"</option>";
		
		// 관찰 ⓑ
/* 		if(year==nowYear){
			yOption += "<option value='" +year +"' selected='selected'>"+year+"</option>";
		}else{
			yOption += "<option value='" +year +"'>"+year+"</option>";
		} */

		// 상황 1: 페이지 최초 요청일 때 → sYear는 null
		//		   현재의 연도와 옵션 값이 같을 때 
		// ==> selected(○)
		
		// 상황 2: 페이지 최초 요청이 아닐 때 → sYear는 null이 아님
		//		   선택된 연도와 옵션 값이 같을 때
		// ==> selected(○)
		
		// 상황 3: 나머지
		// ==> selected(×)
		
		if(sYear==null && year==nowYear)
			yOption += "<option value='" +year +"' selected='selected'>"+year+"</option>";
		else if(sYear!=null && year==Integer.parseInt(sYear))
			yOption += "<option value='" +year +"' selected='selected'>"+year+"</option>";
		else
			yOption += "<option value='" +year +"'>"+year+"</option>";
	}
	// 확인한 날짜로 월 select option 구성
	//------------------------------------------------
 	// <option value="1">1</option>
	// <option value="2">2</option>
	// <option value="3" selected="selected">3</option>
	// 				:
	// <option value="10">10</option>
	// <option value="11">11</option>
	// <option value="12">12</option>
	//------------------------------------------------
	
	String mOption = "";
	for(int month = 1; month<=12; month++)
	{
		// 상황 1: 페이지 최초 요청일 때 → sMonth는 null
				//		   현재의 월과 옵션 값이 같을 때 
				// ==> selected(○)
				
				// 상황 2: 페이지 최초 요청이 아닐 때 → sMonth는 null이 아님
				//		   선택된 월과 옵션 값이 같을 때
				// ==> selected(○)
				
				// 상황 3: 나머지
				// ==> selected(×)
		if(sMonth==null && month==nowMonth)
			mOption += "<option value='" +month +"' selected='selected'>"+month+"</option>";
		else if(sMonth!=null && month==Integer.parseInt(sMonth))
			mOption += "<option value='" +month +"' selected='selected'>"+month+"</option>";
		else
			mOption += "<option value='" +month +"'>"+month+"</option>";
	}

	// 그려야 할 달력의 1일이 무슨 요일인지 확인 필요
	// (만년 달력 구조)
	
	int[] months = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};	//-- 각 월의 최대 날짜
	if(selectYear%4==0 && selectYear%100!=0 || selectYear%400==0)	//-- 윤년
		months[1] = 29;
	
	// 총 날 수 누적 변수
	int nalsu;
	
	// 요일 항목 타이블 배열 구성
	String[] weekNames = {"일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"};
	
	// 입력받은 연도 이전 년도까지의 날 수 계산
	nalsu = (selectYear-1)*365 + (selectYear-1)/4 - (selectYear-1)/100 + (selectYear-1)/400;
	
	// 위 계산 항목에 입력받은 월의 이전 월까지의 날 수 추가
	for(int i=0; i<selectMonth-1; i++){
		nalsu += months[i];
	}
	
	nalsu++;								//-- + 1 (1일까지의 날짜 합산)
	
	int week = nalsu%7;						//-- 요일 변수
	int lastDay = months[selectMonth-1];	//-- 해당 월의 마지막 날짜 변수
	
	// 달력 그리기 ---------------------------------------------------------------------
	String calStr = "";
	
	calStr += "<table border='1'>";
	calStr += "<tr>";
	for(int i = 0 ; i<weekNames.length;i++)
	{
		// 확인
		//calStr += "<th>" + weekNames[i] + "</th>";
		
		if(i==0)															//-- 일요일
			calStr += "<th class='sun'>" + weekNames[i] + "</th>";
		else if(i==6)														//-- 토요일
			calStr += "<th class='sat'>" + weekNames[i] + "</th>";
		else
			calStr += "<th>" + weekNames[i] + "</th>";
	}
	
	calStr += "</tr>";
	
	// 빈 칸 공백 td 발생
	calStr += "<tr>";
	for(int i = 1 ; i<=week;i++)
		calStr +="<td></td>";
	
	// 날짜 td 발생
	for(int i = 1; i<=lastDay; i++)
	{
		week++;							//-- 날짜가 하루씩 처리될 때마다(구성이 이루어질 때 마다)
										//	 요일도 함께 1씩 증가될 수 있도록 처리 CHECK!
		// 확인
		//calStr +="<td>"+i+"</td>";
		
		// 오늘 날짜 확인
		// nowYear, nowMonth, nowDay
		if(selectYear==nowYear&& selectMonth==nowMonth&& i==nowDay){
			if(week%7==1){
				calStr +="<td class='nowSun'>"+i+"</td>";
			}else if(week%7==0){
				calStr +="<td class='nowSat'>"+i+"</td>";
			}else{
				calStr +="<td class='now'>"+i+"</td>";
			}
		}else{
			if(week%7==1){
				calStr +="<td class='sun'>"+i+"</td>";
			}else if(week%7==0){
				calStr +="<td class='sat'>"+i+"</td>";
			}else{
				calStr +="<td>"+i+"</td>";
			}
		}
		
		
		if(week%7==0)
			calStr += "</tr><tr>";
	}
	
	// 빈 칸 공백 td 발생
	for(int i=0; i<=week; i++, week++)
	{
		if(week%7==0)
			break;
		calStr += "<td></td>";
	}
	calStr += "</tr>";
	calStr += "</table>";
	
	
	//---------------------------------------------------------------------- 달력 그리기
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SendAndReceive11_1.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table{border-collapse: collapse;}\r\n");
      out.write("tr>*{text-align: center; padding: 5px;}\r\n");
      out.write("td.now{background-color: aqua; font-weight: bold;}\r\n");
      out.write(".sat{color: blue;}\r\n");
      out.write(".sun{color: red;}\r\n");
      out.write("td.nowSat{background-color: aqua; font-weight: bold; color: blue;}\r\n");
      out.write("td.nowSun{background-color: aqua; font-weight: bold; color: red;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function formCalendar(obj)\r\n");
      out.write("	{\r\n");
      out.write("		// 유효성 검사가 필요할 경우 삽입할 수 있는 영역\r\n");
      out.write("		obj.submit();\r\n");
      out.write("		//-- obj → form 객체\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>JSP를 이용한 데이터 송수신 실습 11</h1>\r\n");
      out.write("	<p>SendAndReceive11_1.jsp● → SendAndReceive11_1.jsp●</p>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	○ 데이터 송수신 실습\r\n");
      out.write("	\r\n");
      out.write("	  - 연도와 월을 입력받아 해당 연월의 달력을 화면에 출력하는 JSP 페이지를 구성한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 단, submit 버튼 없이 이벤트 처리를 할 수 있도록 한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 전송한 내용을 수신하여 출력해주는 형태의 페이지로 구성한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 연도 구성은 현재 연도를 기준으로 이전 10년, 이후 10년으로 구성한다.\r\n");
      out.write("	    (기본적으로 만년 달력을 구성하는데, 현재의 연, 월을 달력 객체를 활용할 수 있도록 한다.)\r\n");
      out.write("\r\n");
      out.write("	  - 월 구성은 1월부터 12월까지로 한다.\r\n");
      out.write("	  \r\n");
      out.write("	  페이지 레이아웃\r\n");
      out.write("	  ---------------------------------------------\r\n");
      out.write("	   2016			 1	\r\n");
      out.write("	  	 :			 :\r\n");
      out.write("	  [2026 ▼] 년 [ 3 ▼] 월\r\n");
      out.write("	  	 :			 :\r\n");
      out.write("	   2036			12\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  ---- 해당 년 월의 달력 -----\r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  \r\n");
      out.write("	  ---------------------------------------------\r\n");
      out.write("	  \r\n");
      out.write("	  - 연도 select나 월 select의 내용이 변화되면\r\n");
      out.write("	    해당 연 월의 달력을 출력하주는 형태의 페이지로 구성한다.\r\n");
      out.write("	    \r\n");
      out.write("	    - 사용자 최초 요청 주소\r\n");
      out.write("	      http://localhost:3306/WebApp06/SendAndReceive11.jsp\r\n");
      out.write("	      \r\n");
      out.write("	   - 물리적 파일 구성\r\n");
      out.write("	     ·SendAndReceive11.jsp\r\n");
      out.write("	\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	1. submit 액션 처리 → 스크립트 제어\r\n");
      out.write("	\r\n");
      out.write("	2. 수신한 데이터에 대한 처리(이전 페이지로부터 데이터 수신)\r\n");
      out.write("	   → 연도, 월\r\n");
      out.write("	   \r\n");
      out.write("	3. Calendar 객체 생성\r\n");
      out.write("	   → 현재의 연, 월, 일 확인\r\n");
      out.write("	   \r\n");
      out.write("	4. 표시할 달력의 연, 월 구성\r\n");
      out.write("	   → 페이지 최초 요청을 감안한 코드 처리 필요\r\n");
      out.write("	   	  (연도 select, 월 select)\r\n");
      out.write("	   	  \r\n");
      out.write("	5. 페이지에 대한 요청이 최초 요청이 아닐 경우\r\n");
      out.write("	   → 사용자가 선택한 값을 활용한 달력의 연, 월 구성\r\n");
      out.write("	   \r\n");
      out.write("	6. 해당 연, 월의 달력 그리기\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("	<!-- ※ form의 action 속성 또는 action 속성값 생략\r\n");
      out.write("			→ 요청 페이지/ 전송 데이터의 수신처는 자기 자신\r\n");
      out.write("	-->\r\n");
      out.write("	<form method=\"post\">\r\n");
      out.write("		<select name=\"year\" id=\"year\" onchange=\"formCalendar(this.form)\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- 	<option value=\"9999\">9999</option>\r\n");
      out.write("			<option value=\"9998\">9998</option>\r\n");
      out.write("			<option value=\"9997\">9997</option>\r\n");
      out.write("			<option value=\"9996\">9996</option> -->\r\n");
      out.write("			");
      out.print( yOption );
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</select> 년\r\n");
      out.write("		<select name=\"month\" id=\"month\" onchange=\"formCalendar(this.form)\">\r\n");
      out.write("<!-- 			<option value=\"99\">99</option>\r\n");
      out.write("			<option value=\"98\">98</option>\r\n");
      out.write("			<option value=\"97\">97</option>\r\n");
      out.write("			<option value=\"96\">96</option> -->\r\n");
      out.write("			");
      out.print( mOption );
      out.write("\r\n");
      out.write("		</select> 월\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<!-- 	달력을 그리게 될 지점 -->\r\n");
      out.write("	");
      out.print( calStr );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
