/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-03 07:16:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Send08_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Send08.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".msg{color: red; font-size: small; display: none;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function formCheck()\r\n");
      out.write("	{\r\n");
      out.write("		//alert(\"확인\");\r\n");
      out.write("		\r\n");
      out.write("		//return false;\r\n");
      out.write("		//return true;\r\n");
      out.write("		\r\n");
      out.write("		// 문서의 내용 점검 → 통과 → return true;  → submit 액션 처리로 제어권 넘김\r\n");
      out.write("		// 문서의 내용 점검 → 실패 → return flase; → submit 액션 처리로 제어권 넘기지 않음\r\n");
      out.write("		\r\n");
      out.write("		// 냅다 뽑기\r\n");
      out.write("	/*	\r\n");
      out.write("		let userId = document.getElementById(\"userId\").value;\r\n");
      out.write("		let userPw = document.getElementById(\"userPw\").value;\r\n");
      out.write("		let userName = document.getElementById(\"userName\").value;\r\n");
      out.write("		let userTel = document.getElementById(\"userTel\").value;\r\n");
      out.write("		\r\n");
      out.write("		if(userId == \"\" || userPw == \"\" || userName == \"\" || userTel == \"\")\r\n");
      out.write("		{			\r\n");
      out.write("			if(!userId){\r\n");
      out.write("				document.getElementById(\"idMsg\").style.display=\"block\";\r\n");
      out.write("			}else{\r\n");
      out.write("				document.getElementById(\"idMsg\").style.display=\"none\";\r\n");
      out.write("			}\r\n");
      out.write("			if(!userPw){\r\n");
      out.write("				document.getElementById(\"pwMsg\").style.display=\"block\";\r\n");
      out.write("			}else{\r\n");
      out.write("				document.getElementById(\"pwMsg\").style.display=\"none\";\r\n");
      out.write("			}\r\n");
      out.write("			if(!userName){\r\n");
      out.write("				document.getElementById(\"nameMsg\").style.display=\"block\";\r\n");
      out.write("			}else{\r\n");
      out.write("				document.getElementById(\"nameMsg\").style.display=\"none\";\r\n");
      out.write("			}\r\n");
      out.write("			if(!userTel){\r\n");
      out.write("				document.getElementById(\"telMsg\").style.display=\"block\";\r\n");
      out.write("			}else{\r\n");
      out.write("				document.getElementById(\"telMsg\").style.display=\"none\";\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			return false;\r\n");
      out.write("			\r\n");
      out.write("		}*/\r\n");
      out.write("		\r\n");
      out.write("		// 배열에 담아서 뽑기\r\n");
      out.write("/* 		let inputIds = [\"userId\", \"userPw\", \"userName\",\"userTel\"];\r\n");
      out.write("		let msgIds = [\"idMsg\", \"pwMsg\", \"nameMsg\", \"telMsg\"];\r\n");
      out.write("		let isValid = true;\r\n");
      out.write("		\r\n");
      out.write("		for (let i = 0; i<inputIds.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			let inputValue = document.getElementById(inputIds[i]).value;\r\n");
      out.write("			let msgElement = document.getElementById(msgIds[i]);\r\n");
      out.write("			\r\n");
      out.write("			if(inputValue == \"\"){\r\n");
      out.write("				msgElement.style.display = \"block\";\r\n");
      out.write("				isValid = false;\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				msgElement.style.display=\"none\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return isValid; */\r\n");
      out.write("		\r\n");
      out.write("		// 모범 답안\r\n");
      out.write("		let userId = document.getElementById(\"userId\");\r\n");
      out.write("		let userPw = document.getElementById(\"userPw\");\r\n");
      out.write("		let userName = document.getElementById(\"userName\");\r\n");
      out.write("		let userTel = document.getElementById(\"userTel\");\r\n");
      out.write("		\r\n");
      out.write("		let idMsg = document.getElementById(\"idMsg\");\r\n");
      out.write("		let pwMsg = document.getElementById(\"pwMsg\");\r\n");
      out.write("		let nameMsg = document.getElementById(\"nameMsg\");\r\n");
      out.write("		let telMsg = document.getElementById(\"telMsg\");\r\n");
      out.write("		\r\n");
      out.write("		// check\r\n");
      out.write("		// <form> 내부의 입력 양식에 대한 값을 변경하고\r\n");
      out.write("		// 다시 이 함수를 호출할 때 마다\r\n");
      out.write("		// 기존에 안내되었던 에러 메시지를 지우고 다시 확인할 수 있도록 처리\r\n");
      out.write("		idMsg.style.display =\"none\";\r\n");
      out.write("		pwMsg.style.display =\"none\";\r\n");
      out.write("		nameMsg.style.display =\"none\";\r\n");
      out.write("		telMsg.style.display =\"none\";\r\n");
      out.write("		\r\n");
      out.write("		if(userId.value ==\"\"){\r\n");
      out.write("			// 확인\r\n");
      out.write("			//alert(\"아이디 미입력\");\r\n");
      out.write("			idMsg.style.display =\"inline\";\r\n");
      out.write("			userId.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(userPw.value ==\"\"){\r\n");
      out.write("			pwMsg.style.display =\"inline\";\r\n");
      out.write("			pwMsg.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(userName.value ==\"\"){\r\n");
      out.write("			nameMsg.style.display =\"inline\";\r\n");
      out.write("			nameMsg.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(userTel.value ==\"\"){\r\n");
      out.write("			telMsg.style.display =\"inline\";\r\n");
      out.write("			telMsg.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>JSP를 이용한 데이터 송수신 실습 08</h1>\r\n");
      out.write("	<p>Send08.jsp● → Receive08.jsp○</p>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("	<form action=\"Receive08.jsp\" method=\"post\" onsubmit=\"return formCheck()\">\r\n");
      out.write("		<table class=\"table\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>아이디(*)</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"text\" id=\"userId\" name=\"userId\" placeholder=\"ex) superman\"/>\r\n");
      out.write("					<span class=\"msg\" id=\"idMsg\">아이디를 입력해야 합니다</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>패스워드(*)</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"password\" id=\"userPw\" name=\"userPw\" placeholder=\"ex) 1234\"/>\r\n");
      out.write("					<span class=\"msg\" id=\"pwMsg\">패스워드를 입력해야 합니다</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>이름(*)</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"text\" id=\"userName\" name=\"userName\" placeholder=\"ex) 홍길동\"/>\r\n");
      out.write("					<span class=\"msg\" id=\"nameMsg\">이름을 입력해야 합니다</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>전화번호(*)</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"tel\" id=\"userTel\" name=\"userTel\" placeholder=\"ex) 010-1234-1234\"/>\r\n");
      out.write("					<span class=\"msg\" id=\"telMsg\">전화번호를 입력해야 합니다</span>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>성별</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<label>\r\n");
      out.write("						<input type=\"radio\" id=\"female\" name=\"userGender\" value=\"여자\" checked=\"checked\" /> 여자\r\n");
      out.write("					</label>\r\n");
      out.write("					<label>\r\n");
      out.write("						<input type=\"radio\" id=\"male\" name=\"userGender\" value=\"남자\" /> 남자\r\n");
      out.write("					</label>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>지역</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<select name=\"userCity\" id=\"userCity\">\r\n");
      out.write("						<option value=\"서울\">서울</option>\r\n");
      out.write("						<option value=\"경기\">경기</option>\r\n");
      out.write("						<option value=\"인천\">인천</option>\r\n");
      out.write("						<option value=\"제주\">제주</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>수강과목</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"checkbox\" name=\"userSubject\" id=\"check1\" value=\"자바기초\" />\r\n");
      out.write("					<label for=\"check1\">자바기초</label>\r\n");
      out.write("					<input type=\"checkbox\" name=\"userSubject\" id=\"check2\" value=\"오라클중급\" />\r\n");
      out.write("					<label for=\"check2\">오라클중급</label>\r\n");
      out.write("					<input type=\"checkbox\" name=\"userSubject\" id=\"check3\" value=\"JDBC\" />\r\n");
      out.write("					<label for=\"check3\">JDBC</label>\r\n");
      out.write("					<input type=\"checkbox\" name=\"userSubject\" id=\"check4\" value=\"JSP심화\" />\r\n");
      out.write("					<label for=\"check4\">JSP심화</label>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th></th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<br />\r\n");
      out.write("					<input type=\"submit\" value=\"회원 가입\" class=\"btn control\" style=\"width: 150px;\"/>\r\n");
      out.write("					<input type=\"reset\" value=\"취소\" class=\"btn control\" style=\"width: 150px;\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
