/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-04 02:13:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SendAndReceive11_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	
	String year = request.getParameter("yearBox");
	String month = request.getParameter("monthBox");
	
	java.util.Calendar cal = java.util.Calendar.getInstance();
	int nowYear = cal.get(java.util.Calendar.YEAR);
	int nowMonth = cal.get(java.util.Calendar.MONTH) + 1;

	int y = 0;
	int m = 0;
	int total = 0;
	int[] eDate =  {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
	int startDay = 0;
	int endDay = 0;
	
	try
	{
		if(year == null || month == null)
		{
			y = nowYear;
			m = nowMonth;
		}else{
			y = Integer.parseInt(year);
			m = Integer.parseInt(month);
		}
		
		total = (y-1) * 365 + (y-1)/4 - (y-1)/100 + (y-1)/400;
				
		if((y%4 == 0 && y%100 !=0) || (y%400 == 0)){
			eDate[1] = 29;
		}
		
		for(int i = 0; i<m-1; i++)
		{
			total += eDate[i];
		}
		
		total += 1;
		
		startDay = total % 7 ;
		endDay = eDate[m-1];
		
		
		
	}catch(Exception e)
	{
		System.out.println(e.toString());
	}



      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SendAndReceive11.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.calendar{margin-top: 20px;}\r\n");
      out.write("	table{border-collapse: collapse;  }\r\n");
      out.write("	tr>*{text-align: center; padding: 5px; width: 15px; height: 15px;}\r\n");
      out.write("	.title{font-size: 18px; font-weight: bold; display:inline-block; width: 200px; text-align: center;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function formChange(obj){\r\n");
      out.write("		obj.submit();	\r\n");
      out.write("		addCalendar();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>JSP를 이용한 데이터 송수신 실습 11</h1>\r\n");
      out.write("	<p>SendAndReceive11.jsp● → SendAndReceive11.jsp●</p>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	○ 데이터 송수신 실습\r\n");
      out.write("	\r\n");
      out.write("	  - 연도와 월을 입력받아 해당 연월의 달력을 화면에 출력하는 JSP 페이지를 구성한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 단, submit 버튼 없이 이벤트 처리를 할 수 있도록 한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 전송한 내용을 수신하여 출력해주는 형태의 페이지로 구성한다.\r\n");
      out.write("	  \r\n");
      out.write("	  - 연도 구성은 현재 연도를 기준으로 이전 10년, 이후 10년으로 구성한다.\r\n");
      out.write("	    (기본적으로 만년 달력을 구성하는데, 현재의 연, 월을 달력 객체를 활용할 수 있도록 한다.)\r\n");
      out.write("\r\n");
      out.write("	  - 월 구성은 1월부터 12월까지로 한다.\r\n");
      out.write("	  \r\n");
      out.write("	  페이지 레이아웃\r\n");
      out.write("	  ---------------------------------------------\r\n");
      out.write("	   2016			 1	\r\n");
      out.write("	  	 :			 :\r\n");
      out.write("	  [2026 ▼] 년 [ 3 ▼] 월\r\n");
      out.write("	  	 :			 :\r\n");
      out.write("	   2036			12\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  ---- 해당 년 월의 달력 -----\r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  ----------------------------\r\n");
      out.write("	  \r\n");
      out.write("	  ---------------------------------------------\r\n");
      out.write("	  \r\n");
      out.write("	  - 연도 select나 월 select의 내용이 변화되면\r\n");
      out.write("	    해당 연 월의 달력을 출력하주는 형태의 페이지로 구성한다.\r\n");
      out.write("	    \r\n");
      out.write("	    - 사용자 최초 요청 주소\r\n");
      out.write("	      http://localhost:3306/WebApp06/SendAndReceive11.jsp\r\n");
      out.write("	      \r\n");
      out.write("	   - 물리적 파일 구성\r\n");
      out.write("	     ·SendAndReceive11.jsp\r\n");
      out.write("	\r\n");
      out.write(" -->\r\n");
      out.write("<div>\r\n");
      out.write("	<form method=\"post\">\r\n");
      out.write("		<div class=\"inputWrap\">\r\n");
      out.write("			<select name=\"yearBox\" id=\"yearBox\" onchange=\"formChange(this.form)\">\r\n");
      out.write("			");

				for(int i = y - 10; i<= y + 10; i++)
				{
					if(i == y)
					{
			
      out.write("\r\n");
      out.write("						<option value=\"");
      out.print( i);
      out.write("\" selected=\"selected\">");
      out.print( i );
      out.write("</option>\r\n");
      out.write("			");

					}
			
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print( i);
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</option>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			</select>년\r\n");
      out.write("			<select name=\"monthBox\" id=\"monthBox\" onchange=\"formChange(this.form)\">\r\n");
      out.write("			");

				for(int i = 1; i<= 12; i++){
					if(i== m){
			
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print( i);
      out.write("\" selected=\"selected\">");
      out.print(i );
      out.write("</option>\r\n");
      out.write("			");

					}
			
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print( i);
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</option>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			</select>월\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"calendar\">\r\n");
      out.write("<p class=\"title\"><span>");
      out.print( y );
      out.write("</span>년 <span>");
      out.print( m );
      out.write("</span>월</p>\r\n");
      out.write("	<table border=\"1\" id=\"tableBox\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>일</th>\r\n");
      out.write("			<th>월</th>\r\n");
      out.write("			<th>화</th>\r\n");
      out.write("			<th>수</th>\r\n");
      out.write("			<th>목</th>\r\n");
      out.write("			<th>금</th>\r\n");
      out.write("			<th>토</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		");

		for(int i = 0; i < startDay; i++)
		{
			out.print("<td></td>");
		}
		
		int cnt = startDay;
		
		for(int i = 1; i<= endDay; i++){
			out.print("<td>"+ i +"</td>");
			cnt++;
			
			if(cnt%7 == 0){
				out.print("</tr><tr>");
			}
		}
		if(cnt%7 !=0){
			for(int i = 0 ; i< 7-(cnt%7); i++)
			{
				out.print("<td></td>");
			}
		}
		
		
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
