/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-04 08:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class SendAndReceive12_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//-- 이전 페이지로부터 넘어온 데이터 수신
	String strYear = request.getParameter("year");
	String strMonth = request.getParameter("month");

	// 달력 객체 생성
	Calendar cal = Calendar.getInstance();
	
	// 오늘의 날짜 확인
	int nowYear = cal.get(Calendar.YEAR);
	int nowMonth = cal.get(Calendar.MONTH)+1;
	int nowDay = cal.get(Calendar.DAY_OF_WEEK);

	// 표시할 달력의 연, 월 구성
	int year = nowYear;
	int month = nowMonth;
	
	// 최초 요청이 아니라면
	if(strYear != null)
		year = Integer.parseInt(strYear);
	if(strMonth != null)
		month = Integer.parseInt(strMonth);
	
	
	// 이전
	int preYear = year;
	int preMonth = month-1;
	
	if(preMonth<1){
		preYear = year-1;
		preMonth = 12;
	}
	
	// 다음
	int nextYear = year;
	int nextMonth = month+1;
	
	if(nextMonth>12){
		nextYear = year+1;
		nextMonth = 1;
	}
	
	// 표시할 달력 세팅
	cal.set(year, month-1, 1);
	int startDay = 1;
	
	// 해당 연, 월의 마지막 날짜 구하기
	int endDay = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
	
	// 요일 확인
	int week = cal.get(Calendar.DAY_OF_WEEK);
	
	


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SendAndReceive12_1.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a{text-decoration: none;}\r\n");
      out.write("td{text-align: center;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 확인 -->\r\n");
      out.write("<!-- <h2><a href=\"SendAndReceive12_1.jsp?year=2000&month=12\">버튼</a></h2> -->\r\n");
      out.write("<div>\r\n");
      out.write("	<table class=\"table\" style=\"text-align: center;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<a href=\"SendAndReceive12_1.jsp?year=");
      out.print( preYear);
      out.write("&month=");
      out.print( preMonth);
      out.write("\">◀</a>\r\n");
      out.write("				\r\n");
      out.write("				<!-- <b>2026년 3월</b> -->\r\n");
      out.write("				<b>");
      out.print(year );
      out.write('년');
      out.write(' ');
      out.print(month );
      out.write("월</b>\r\n");
      out.write("				\r\n");
      out.write("				<a href=\"SendAndReceive12_1.jsp?year=");
      out.print( nextYear);
      out.write("&month=");
      out.print( nextMonth);
      out.write("\">▶</a>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<table class=\"table\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th style=\"background-color:#ededed; color:red;\">일</th>\r\n");
      out.write("			<th style=\"background-color:#ededed;\">월</th>\r\n");
      out.write("			<th style=\"background-color:#ededed;\">화</th>\r\n");
      out.write("			<th style=\"background-color:#ededed;\">수</th>\r\n");
      out.write("			<th style=\"background-color:#ededed;\">목</th>\r\n");
      out.write("			<th style=\"background-color:#ededed;\">금</th>\r\n");
      out.write("			<th style=\"background-color:#ededed; color:blue;\">토</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

			int newLine = 0;	// check
		
			out.print("<tr>");
			for(int i = 1; i< week; i++){
				out.print("<td style='background-color: #f8f8f8;'>&nbsp;</td>");
				newLine++; 		// check
			}
			for(int i=startDay; i<=endDay; i++){
				String fontColor = (newLine==0)? "red" : (newLine==6) ? "blue" : "#333";
				String bgColor = (nowYear==year)&&(nowMonth==month)&&(nowDay==i)? "#d2d4ba" : "#f8f8f8";
				
				out.print("<td style='background-color: " + bgColor + "'><span style='color:" + fontColor + "'>"+i+"</td>");
				newLine++;		// check
				
				if(newLine==7 && i!=endDay){
					out.print("</tr><tr>");
					newLine = 0;
				}
			}
			
			while(newLine < 7){
				out.print("<td style='background-color: #f8f8f8;'>&nbsp;</td>");
				newLine++;		//check
			}
			out.print("</tr>");
		
		
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
