/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2026-03-04 07:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class SendAndReceive12_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String sYear = request.getParameter("year");
	String sMonth = request.getParameter("month");

	Calendar cal = Calendar.getInstance();
	
	int nowYear = cal.get(Calendar.YEAR);
	int nowMonth = cal.get(Calendar.MONTH)+1;
	int nowDay = cal.get(Calendar.DAY_OF_WEEK);
	int nowDate = cal.get(Calendar.DATE);
	int selectYear, selectMonth;
	
	if (sYear == null || sYear.equals("") || sMonth == null || sMonth.equals("")) {
        selectYear = nowYear;
        selectMonth = nowMonth;
    } else {
        selectYear = Integer.parseInt(sYear);
        selectMonth = Integer.parseInt(sMonth);
    }
    cal.set(selectYear, selectMonth - 1, 1);
    
	String[] weekNames = {"일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"};
	int startDay = cal.get(Calendar.DAY_OF_WEEK);     // 1일의 요일 
    int lastDay = cal.getActualMaximum(Calendar.DATE); // 해당 월의 마지막 날짜
	
	// 달력 그리기
	String calStr ="";
	
	calStr += "<table border='1'>";
	calStr += "<tr>";
	for(int i = 0; i<weekNames.length; i++){
		//calStr += "<th>" + weekNames[i] +"</th>";
		if(i==0)															
			calStr += "<th class='sun'>" + weekNames[i] + "</th>";
		else if(i==6)														
			calStr += "<th class='sat'>" + weekNames[i] + "</th>";
		else
			calStr += "<th>" + weekNames[i] + "</th>";
	}
	calStr += "</tr><tr>";
	for(int i = 1 ; i<startDay;i++)
		calStr +="<td></td>";
	
	int week = startDay;
	for(int i = 1; i<=lastDay; i++, week++)
	{
		
		if(selectYear==nowYear&& selectMonth==nowMonth&& i==nowDay){
			if(week%7==1){
				calStr +="<td class='nowSun'>"+i+"</td>";
			}else if(week%7==0){
				calStr +="<td class='nowSat'>"+i+"</td>";
			}else{
				calStr +="<td class='now'>"+i+"</td>";
			}
		}else{
			if(week%7==1){
				calStr +="<td class='sun'>"+i+"</td>";
			}else if(week%7==0){
				calStr +="<td class='sat'>"+i+"</td>";
			}else{
				calStr +="<td>"+i+"</td>";
			}
		}
		//calStr += "<td>"+ i + "</td>";
		if(week%7==0){
			calStr += "</tr><tr>"; 
		}
	}
	
	for(int i=1; i<=week; i++, week++)
	{
		if((week-1)%7==0)
			break;
		calStr += "<td></td>";
	}
	calStr += "</tr>";
	calStr += "</table>";
	


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SendAndReceive12.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".wrap{width: 456px; }\r\n");
      out.write("#calForm{margin: 0 auto; }\r\n");
      out.write("form{height: 50px;  width: 200px; }\r\n");
      out.write("form>*{float: left; line-height: 50px;}\r\n");
      out.write("p{background-color: #fff; display:inline-block; height: 50px; margin: 0 2px;}\r\n");
      out.write("button{background-color: #fff; border:none; font-size: 20px; cursor: pointer;}\r\n");
      out.write("table{border-collapse: collapse;}\r\n");
      out.write("th{background-color: #ededed;}\r\n");
      out.write("tr>*{text-align: center; padding: 5px;}\r\n");
      out.write("td.now{background-color: aqua; font-weight: bold;}\r\n");
      out.write(".sat{color: blue;}\r\n");
      out.write(".sun{color: red;}\r\n");
      out.write("td.nowSat{background-color: aqua; font-weight: bold; color: blue;}\r\n");
      out.write("td.nowSun{background-color: aqua; font-weight: bold; color: red;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function changeDate(num){\r\n");
      out.write("		let yearStr = document.getElementById(\"year\");\r\n");
      out.write("		let monthStr = document.getElementById(\"month\");\r\n");
      out.write("		let year = parseInt(yearStr.value);\r\n");
      out.write("		let month = parseInt(monthStr.value)+num;\r\n");
      out.write("\r\n");
      out.write("		if(month < 1){\r\n");
      out.write("			year--;\r\n");
      out.write("			month = 12;\r\n");
      out.write("		}else if(month > 12){\r\n");
      out.write("			year++;\r\n");
      out.write("			month = 1;\r\n");
      out.write("		}\r\n");
      out.write("		yearStr.value = year;\r\n");
      out.write("		monthStr.value = month;\r\n");
      out.write("		\r\n");
      out.write("		document.getElementById(\"calForm\").submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>JSP를 이용한 데이터 송수신 실습 12</h1>\r\n");
      out.write("	<p>SendAndReceive12.jsp● → SendAndReceive12.jsp●</p>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
      out.write("<!-- \r\n");
      out.write("	○ 데이터 송수신 실습\r\n");
      out.write("	\r\n");
      out.write("		- 사용자가 선택한 연도와 월에 대해 달력을 구성하는 JSP 페이지를 구성한다.\r\n");
      out.write("		- 단, submit 버튼 없이 이벤트 처리를 할 수 있도록 하낟.\r\n");
      out.write("		- 전송한 내용을 자신 페이지로 수신하여 출력해주는 형태의 단독 페이지로 구성한다.\r\n");
      out.write("		\r\n");
      out.write("		페이지 레이아웃\r\n");
      out.write("		-------------------------------------------------------\r\n");
      out.write("		\r\n");
      out.write("		       ◀ 2026년 3월 ▶\r\n");
      out.write("		  ----------------------------\r\n");
      out.write("		  ---- 해당 년 월의 달력 -----\r\n");
      out.write("		  ----------------------------\r\n");
      out.write("		  ----------------------------\r\n");
      out.write("		-------------------------------------------------------\r\n");
      out.write("		\r\n");
      out.write("		- ◀▶ 클릭 시 해당 년 월의 달력을 출력해주는 형태의 페이지로 구성한다.\r\n");
      out.write("		- 사용자 최초 요청 주소\r\n");
      out.write("	      http://localhost:3306/WebApp06/SendAndReceive12.jsp\r\n");
      out.write("	      \r\n");
      out.write("	   - 물리적 파일 구성\r\n");
      out.write("	     ·SendAndReceive12.jsp\r\n");
      out.write("	\r\n");
      out.write(" -->\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("	<form method=\"post\" id=\"calForm\">\r\n");
      out.write("		<button class=\"prev\" onclick=\"changeDate(-1)\">◀</button>\r\n");
      out.write("		<div class=\"dateWrap\">		\r\n");
      out.write("			<input type=\"hidden\" id=\"year\" name=\"year\" value=\"");
      out.print( selectYear );
      out.write('"');
      out.write('>');
      out.print( selectYear );
      out.write("년\r\n");
      out.write("			<input type=\"hidden\" id=\"month\" name=\"month\" value=\"");
      out.print( selectMonth );
      out.write('"');
      out.write('>');
      out.print( selectMonth );
      out.write("월\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"next\" onclick=\"changeDate(1)\">▶</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.print( calStr );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
